# For more info on HTTP files go to https://aka.ms/vs/httpfile
@server = https://localhost:7048

GET {{server}}/recipe

###

POST {{server}}/recipe
Content-Type: application/json

{
  "name": "Cookies",
  "instructions": "Bake them",
  "minutesToMake": 10,
  "sourceUrl": "http://www.cookies.com",
  "ingredients": [
    {
      "name": "Chocolate",
      "quantity": 15,
      "unit": "25# Bags"
    }
  ],
  "imageUrl": "https://images.pexels.com/photos/230325/pexels-photo-230325.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
}

###

DELETE {{server}}/recipe/1
