# For more info on HTTP files go to https://aka.ms/vs/httpfile
@server = https://localhost:7048

GET {{server}}/recipe

###

POST {{server}}/recipe
Content-Type: application/json

{
  "name": "Cookies",
  "instructions": "Mix them up, stick them in the oven at 350 for 20 minutes, wait as long as you're able but not more than 30 seconds, then eat them."
}

###

POST {{server}}/ingredient
Content-Type: application/json

{
  "name": "Flour",
  "quantity": 2,
  "unit": "cups"
}

###

POST {{server}}/recipeingredient
Content-Type: application/json

{
  "recipeId": 1,
  "ingredientId": 1
}